### ISSUE TITLE
XML parsing error

### ISSUE THREAD

**Issue by cjthomas730** [kapadia/sentinels#1]
Hello, I'm trying to find Sentinel 1 imagery and I'm getting an xml parsing error.  The feature collection generation code is below and the error message is at the bottom.  I noticed that there aren't any tagged releases and the readme says `TBD` for the Python API so is the search feature just not finished yet?

``` python
import json
x, y = (3.291215, 51.422819)
xmin = x - 0.01
ymin = y - 0.01
xmax = x + 0.01
ymax = y + 0.01

fc = {
    'type': 'FeatureCollection',
    'features': [
        {
            'type': 'Feature',
            'properties': {},
            'geometry': {
                "type": "Polygon",
                "coordinates": [
                    [
                        (xmin, ymin),
                        (xmin, ymax),
                        (xmax, ymax),
                        (xmax, ymin)
                    ]]
            }
        }
    ]
}
print(json.dumps(fc))
```

Here's the error:

``` console
$ python fc.py  | sentinels search
Traceback (most recent call last):
  File "/usr/local/bin/sentinels", line 9, in <module>
    load_entry_point('sentinels==0.0.1', 'console_scripts', 'sentinels')()
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 664, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 644, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "/Users/Christian/sentinels/sentinels/scripts/cli.py", line 80, in search
    swath_identifier=swath_identifier
  File "/Users/Christian/sentinels/sentinels/api.py", line 119, in search
    return parse.search(r.text)
  File "/Users/Christian/sentinels/sentinels/parse.py", line 137, in search
    root = ElementTree.fromstring(response)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
xml.etree.ElementTree.ParseError: mismatched tag: line 1, column 1049
```

/ cc @geowurster

**Comment by kapadia** [comment]
@cjthomas730 Looks like there are a few things going on here.

The geojson that you're using to search does not define a closed polygon. The sentinels archive uses WKT, which is also required to be closed. The function that's converting from geojson to WKT - [sentinels.format](https://github.com/kapadia/sentinels/blob/4eb694225c29acc5f2d0ed81791522e34b1ad010/sentinels/format.py#L6-L24) - assumes the geojson is valid and proceeds to construct the WKT string.

When your query is submitted to the archive, it errors out, returning:

```
<html><head><title>Apache Tomcat/7.0.47 - Error report</title><style><!--H1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} H2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} H3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} BODY {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} B {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} P {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;}A {color : black;}A.name {color : black;}HR {color : #525D76;}--></style> </head><body><h1>HTTP Status 500 - Server returned HTTP response code: 400 for URL: http://localhost:8081//solr/dhus/select?q=(footprint:&quot;Intersects(POLYGON%20((3.2812150000000000%2051.4128189999999989,%203.2812150000000000%2051.4328189999999950,%203.3012149999999996%2051.4328189999999950,%203.3012149999999996%2051.4128189999999989)))&quot;)%20&amp;wt=xslt&amp;tr=opensearch_atom.xsl&amp;dhusLongName=Sentinels%20Scientific%20Data%20Hub&amp;dhusServer=https://scihub.esa.int/dhus/&amp;originalQuery=footprint:&quot;Intersects(POLYGON%20((3.2812150000000000%2051.4128189999999989,%203.2812150000000000%2051.4328189999999950,%203.3012149999999996%2051.4328189999999950,%203.3012149999999996%2051.4128189999999989)))&quot;&amp;rows=1</h1><HR size="1" noshade="noshade"><p><b>type</b> Exception report</p><p><b>message</b> <u>Server returned HTTP response code: 400 for URL: http://localhost:8081//solr/dhus/select?q=(footprint:&quot;Intersects(POLYGON%20((3.2812150000000000%2051.4128189999999989,%203.2812150000000000%2051.4328189999999950,%203.3012149999999996%2051.4328189999999950,%203.3012149999999996%2051.4128189999999989)))&quot;)%20&amp;wt=xslt&amp;tr=opensearch_atom.xsl&amp;dhusLongName=Sentinels%20Scientific%20Data%20Hub&amp;dhusServer=https://scihub.esa.int/dhus/&amp;originalQuery=footprint:&quot;Intersects(POLYGON%20((3.2812150000000000%2051.4128189999999989,%203.2812150000000000%2051.4328189999999950,%203.3012149999999996%2051.4328189999999950,%203.3012149999999996%2051.4128189999999989)))&quot;&amp;rows=1</u></p><p><b>description</b> <u>The server encountered an internal error that prevented it from fulfilling this request.</u></p><p><b>exception</b> <pre>java.io.IOException: Server returned HTTP response code: 400 for URL: http://localhost:8081//solr/dhus/select?q=(footprint:&quot;Intersects(POLYGON%20((3.2812150000000000%2051.4128189999999989,%203.2812150000000000%2051.4328189999999950,%203.3012149999999996%2051.4328189999999950,%203.3012149999999996%2051.4128189999999989)))&quot;)%20&amp;wt=xslt&amp;tr=opensearch_atom.xsl&amp;dhusLongName=Sentinels%20Scientific%20Data%20Hub&amp;dhusServer=https://scihub.esa.int/dhus/&amp;originalQuery=footprint:&quot;Intersects(POLYGON%20((3.2812150000000000%2051.4128189999999989,%203.2812150000000000%2051.4328189999999950,%203.3012149999999996%2051.4328189999999950,%203.3012149999999996%2051.4128189999999989)))&quot;&amp;rows=1
    sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1627)
    fr.gael.dhus.api.SearchController.search(SearchController.java:152)
    fr.gael.dhus.api.SearchController$$FastClassBySpringCGLIB$$ed5895d9.invoke(&lt;generated&gt;)
    org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
    org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:717)
    org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
    org.springframework.security.access.intercept.aopalliance.MethodSecurityInterceptor.invoke(MethodSecurityInterceptor.java:64)
    org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
    org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:653)
    fr.gael.dhus.api.SearchController$$EnhancerBySpringCGLIB$$83a1ccd6.search(&lt;generated&gt;)
    sun.reflect.GeneratedMethodAccessor313.invoke(Unknown Source)
    sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    java.lang.reflect.Method.invoke(Method.java:606)
    org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221)
    org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:137)
    org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:110)
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandleMethod(RequestMappingHandlerAdapter.java:777)
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:706)
    org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
    org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:943)
    org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:877)
    org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:966)
    org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:857)
    javax.servlet.http.HttpServlet.service(HttpServlet.java:621)
    org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:842)
    javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
    org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
    fr.gael.dhus.spring.CacheControlFilter.doFilter(CacheControlFilter.java:47)
    org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
    org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:118)
    org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:84)
    org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
    org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:113)
    org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
    org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:103)
    org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
    org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:113)
    org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
    org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:154)
    org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
    org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:45)
    org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
    org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilter(BasicAuthenticationFilter.java:201)
    org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
    org.springframework.security.web.authentication.preauth.AbstractPreAuthenticatedProcessingFilter.doFilter(AbstractPreAuthenticatedProcessingFilter.java:94)
    org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
    org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:110)
    org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
    org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:50)
    org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
    org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
    org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:87)
    org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
    org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:192)
    org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:160)
    org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:344)
    org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:261)
</pre></p><p><b>note</b> <u>The full stack trace of the root cause is available in the Apache Tomcat/7.0.47 logs.</u></p><HR size="1" noshade="noshade"><h3>Apache Tomcat/7.0.47</h3></body></html>
```

Resubmit your query with correctly formatted geojson, and you should receive a list of results. It's a little confusing that this library throws `ParseError`, so I'll change it to raise an error on a bad response code.

This is very much a work in progress. You'll notice downloading data is not yet supported. Searching, however, is mostly functional, except for the lack of docs. You can get an idea on the allowed search parameters from the usage info:

```
$ sentinels search --help
Usage: sentinels search [OPTIONS] [AOI]

  Search products hosted by the Scientific Data Hub.

Options:
  --rows INTEGER                  The number of results to return
  --offset INTEGER                The number of rows to offset the results
  --platform-name TEXT            The satellite platform name (e.g.
                                  Sentinel-1)
  --begin-position TEXT...        A time interval search based on the sensing
                                  start time
  --end-position TEXT...          A time interval search based on the sensing
                                  end time
  --ingestion-date TEXT...        A time interval search based on the time of
                                  publication of the product on the Data Hub.
  --filename TEXT                 The product filename
  --orbit-number TEXT             Absolute orbit number of the oldest line
                                  within the image data
  --last-orbit-number TEXT        Absolute orbit number of the most recent
                                  line within the image data
  --orbit-direction [ascending|descending]
                                  Direction of the orbit
  --polarisation-mode, --polarization-mode [HH|VV|HV|VH|HH HV|VV VH]
                                  Polarizations for the S1 SAR instrument
  --product-type [SLC|GRD|OCN|S2MSI1C]
  --relative-orbit-number TEXT    Relative orbit number of the oldest line
                                  within the image data
  --last-relative-orbit-number TEXT
                                  Relative orbit number of the most recent
                                  line within the image data
  --sensor-operational-mode [SM|IW|EW]
                                  The SAR instrument imaging modes
  --swath-identifier [S1|S2|S3|S4|S5|S6|IW|IW1|IW2|IW3|EW|EW1|EW2|EW3|EW4|EW5]
                                  Search all valid swath identifiers for the
                                  Sentinel-1 SAR instrument. The S1-S6 swaths
                                  apply to SM products, the IW and IW1-3
                                  swaths apply to IW products (IW is used for
                                  detected IW products where the 3 swaths are
                                  merged into one image), the EW and EW1-5
                                  swaths apply to EW products (EW is used for
                                  detected EW products where the 5 swaths are
                                  merged into one image).
  --help                          Show this message and exit.
```

happy to take suggestions too.

**Comment by kapadia** [comment]
Additionally, looks like the service is undergoing maintenance:

https://scihub.esa.int/news/News00036

**Comment by kapadia** [comment]
An exception is now raised if the server returns 400 or 500s. In this case, with a malformed request, the exception will be a little more coherent. It will look like:

```
$ sentinels search aoi.geojson
Traceback (most recent call last):
  File "/Users/amitkapadia/anaconda/envs/sentinels/bin/sentinels", line 9, in <module>
    load_entry_point('sentinels==0.0.1.dev0', 'console_scripts', 'sentinels')()
  File "/Users/amitkapadia/anaconda/envs/sentinels/lib/python2.7/site-packages/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/Users/amitkapadia/anaconda/envs/sentinels/lib/python2.7/site-packages/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/Users/amitkapadia/anaconda/envs/sentinels/lib/python2.7/site-packages/click/core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/amitkapadia/anaconda/envs/sentinels/lib/python2.7/site-packages/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/amitkapadia/anaconda/envs/sentinels/lib/python2.7/site-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/Users/amitkapadia/Projects/sentinels/sentinels/scripts/cli.py", line 80, in search
    swath_identifier=swath_identifier
  File "/Users/amitkapadia/Projects/sentinels/sentinels/api.py", line 124, in search
    r.raise_for_status()
  File "/Users/amitkapadia/anaconda/envs/sentinels/lib/python2.7/site-packages/requests/models.py", line 851, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error
```
